default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: trapezi_dev
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>





test:
  <<: *default
  database: trapezi_test
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>



production:
  primary: &primary_production
    <<: *default
    database: trapezi_backend_production
    username: trapezi_backend
    password: <%= ENV["TRAPEZI_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: trapezi_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: trapezi_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: trapezi_backend_production_cable
    migrations_paths: db/cable_migrate
